wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712716990.0
    t:
      1:
      - 1
      - 5
      - 11
      - 35
      - 41
      - 49
      - 53
      - 55
      - 63
      - 66
      - 71
      2:
      - 1
      - 5
      - 11
      - 35
      - 41
      - 49
      - 53
      - 55
      - 63
      - 66
      - 71
      3:
      - 13
      - 23
      - 61
      4: 3.11.3
      5: 0.16.5
      6: 4.39.3
      8:
      - 5
      13: linux-x86_64
composer_version:
  desc: null
  value: 0.17.2
composer_commit_hash:
  desc: null
  value: None
num_nodes:
  desc: null
  value: 1
num_gpus_per_node:
  desc: null
  value: 1
node_name:
  desc: null
  value: unknown because NODENAME environment variable not set
rank_zero_seed:
  desc: null
  value: 1
