wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712105026.327654
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 66
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 66
      3:
      - 13
      - 23
      4: 3.11.3
      5: 0.15.4
      8:
      - 5
