_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 66
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 66
                - 71
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.5
            "6": 4.48.1
            "8":
                - 5
            "12": 0.19.5
            "13": linux-x86_64
