wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712130534.719333
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 66
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 66
      3:
      - 2
      - 13
      - 23
      4: 3.11.3
      5: 0.15.4
      8:
      - 5
composer_version:
  desc: null
  value: 0.17.2
composer_commit_hash:
  desc: null
  value: None
num_nodes:
  desc: null
  value: 1
num_gpus_per_node:
  desc: null
  value: 1
node_name:
  desc: null
  value: unknown because NODENAME environment variable not set
rank_zero_seed:
  desc: null
  value: 1
